---
title: "Resources for Learning R and Data Science"
author: "Richard G. Gardiner"
date: "2/27/2019"
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## {.tabset}


### Main Data Science

#### Books

- [R for Data Science](https://r4ds.had.co.nz/)
- [Exploratory Data Analysis with R](https://leanpub.com/exdata)
- [Introduction to Machine Learning with R](https://lgatto.github.io/IntroMachineLearningWithR/index.html)
- [Statistical Intference via Data Science](https://moderndive.com/)
- [An Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Seventh%20Printing.pdf)
- [Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/printings/ESLII_print12.pdf)
- [R Programming for Data Science](https://leanpub.com/rprogramming)
- [The Art of Data Science](https://leanpub.com/artofdatascience)
- [Practical Data Science with R](https://github.com/louisville-rstats/ebooks/blob/master/Practical%20Data%20Science%20with%20R%20-%20Nina%20Zumel%20John%20Mount.pdf)
- [Introduction to Data Science](https://rafalab.github.io/dsbook/)
- [Principles of Strategic Data Science](https://leanpub.com/strategic_data_science/)

#### Websites

- [Keras for R](https://blog.rstudio.com/2017/09/05/keras-for-r/)
- [Real-World Data Science](https://www.slideshare.net/ShirinGlander/realworld-data-science-fraud-detection-customer-churn-predictive-maintenance)
- [Seeing Theory (Probabilities)](https://seeing-theory.brown.edu/basic-probability/index.html)
- [R Bloggers](https://www.r-bloggers.com/)
- [Variance Explained](http://varianceexplained.org/)
- [Hooked on Data](https://hookedondata.org/)
- [Data Science and AI Flash Cards](https://chrisalbon.com/)
- [R Resources (free courses, books, tutorials, & cheat sheets)](https://paulvanderlaken.com/2017/08/10/r-resources-cheatsheets-tutorials-books/)


#### Intersting Stories

- [What Does Your Credit-Card Company Know About You?](https://www.nytimes.com/2009/05/17/magazine/17credit-t.html)
- [Tentpoles of Data Science](https://simplystatistics.org/2019/01/18/the-tentpoles-of-data-science/)
- [Duke Saga](https://simplystatistics.org/2018/04/23/what-can-we-learn-from-data-analysis-failures/)
- [WHy Women Are Flourishing in R Community But Lagging in Python](https://reshamas.github.io/why-women-are-flourishing-in-r-community-but-lagging-in-python/)
- [Here's Waldo](http://www.randalolson.com/2015/02/03/heres-waldo-computing-the-optimal-search-strategy-for-finding-waldo/)
- [10 Things R can do that might surprise you](https://simplystatistics.org/2019/03/13/10-things-r-can-do-that-might-surprise-you/) 


#### Podcasts

- DataFramed
- Not so Standard Deviations
- Partially Derivative
- Talking Machines
- O'Reilly Data Show
- Becoming a Data Scientist




### Programming

#### Books

- [Advanced R (Programming)](http://adv-r.had.co.nz/)
- [R Packages](http://r-pkgs.had.co.nz/) 
- [Modern R with the Tidyverse](https://b-rodrigues.github.io/modern_R/)
- [Programming with R](https://swcarpentry.github.io/r-novice-inflammation/)


#### Websites

- [R Studio Conference Slides](https://blog.rstudio.com/2019/02/06/rstudio-conf-2019-workshops/?utm_content=buffer6f00e&utm_medium=social&utm_source=twitter&utm_campaign=buffer)
- [R Studio: Online Learning](https://www.rstudio.com/online-learning/#shiny)





### Data Visualization

#### Books

- [Fundamentals of Data Visualization](https://serialmentor.com/dataviz/)
- [Data Visualization](http://socviz.co/index.html#preface)
- [R Graphics Cookbook](http://www.cookbook-r.com/Graphs/)
- [Data Visualization Cheet Sheet (KD Nuggets)](https://www.kdnuggets.com/2018/08/data-visualization-cheatsheet.html)


#### Websites

- [Information is Beautiful](https://informationisbeautiful.net/)
- [The Pudding](https://pudding.cool/)
- [Economist: Mistakes we've made](https://medium.economist.com/mistakes-weve-drawn-a-few-8cdd8a42d368)



#### Podcasts

- Data Stories




### Basic R 

#### Books

- [R Cookbook](http://www.bagualu.net/wordpress/wp-content/uploads/2015/10/R_Cookbook.pdf)
- [Simple R](https://cran.r-project.org/doc/contrib/Verzani-SimpleR.pdf)

#### Curated Classes

- [Intro to Data Management in R](https://cran.r-project.org/doc/contrib/Verzani-SimpleR.pdf)

#### Podcasts

- The R-Podcast





### Specific Methods

#### Books

- [Text Mining with R](https://www.tidytextmining.com/)
- [Introduction to Empirical Bayes](https://gumroad.com/l/empirical-bayes)
- [A/B Testing](https://towardsdatascience.com/data-science-you-need-to-know-a-b-testing-f2f12aff619a)
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)
- [Happy Git and GitHub for the useR](https://happygitwithr.com/)
- [Broadening Your Statistical Horizons: GLMS](https://bookdown.org/roback/bookdown-bysh/) 
- [A Language, Not a Letter: Learning Statistics in R](https://ademos.people.uic.edu/)
- [Lab Notes for Statistics for Social Sciences II](https://bookdown.org/egarpor/SSS2-UC3M/)
- [Book Down](https://bookdown.org/yihui/bookdown/)

#### Interesting Stories

- [Difficulty with Measurment](https://www.newyorker.com/magazine/2011/02/14/the-order-of-things)
- [The Median isn't the Message](https://people.umass.edu/biep540w/pdf/Stephen%20Jay%20Gould.pdf)
- [Mosiac Effect](https://gcn.com/articles/2014/05/14/fose-mosaic-effect.aspx?m=1)
- [The Monty Hall Problem](https://www.nytimes.com/2008/04/08/science/08monty.html)
- [Tweets about Navy Armor Problem](https://mobile.twitter.com/ricfulop/status/1101976862325174276?s=21)
- [Probabilities and SIDS](http://tutorials.iq.harvard.edu/Unmaintained/StatsCrashCourse/Ray_Hill_discussing_Sally_Clark.pdf)
- [The Hot Hand in Basketball: On the Misperception of Random Sequences](http://www.cs.colorado.edu/~mozer/Teaching/syllabi/7782/readings/gilovich%20vallone%20tversky.pdf)
- [Psychology Reproducibility Crisis](https://www.npr.org/sections/health-shots/2018/08/27/642218377/in-psychology-and-other-social-sciences-many-studies-fail-the-reproducibility-te)


#### Articles

- [Heteroskedasticity](https://datascienceplus.com/how-to-detect-heteroscedasticity-and-rectify-it/)
- [Multi Level Modeling: Reading List](http://jakewestfall.org/blog/index.php/2015/06/20/reading-list-introduction-to-linear-mixed-models-for-cognitive-scientists/)
- [Multi Level Workshop](http://www.page-gould.com/mlm/aps/)
- [NLP](https://mlwhiz.com/blog/2019/01/17/deeplearning_nlp_preprocess/)
- [Guidelines for A/B Testing](https://hookedondata.org/guidelines-for-ab-testing/)
- [10 Guidelines for A/B Testing](https://docs.google.com/presentation/d/19_x0RJqz10ZPCC29IVkp6mDEJiitXglSgkdM4DAKW6Q/mobilepresent?slide=id.g480fdbf3d0_2_28)

#### Podcasts

- Linear Digressions
- Learning Machines 101



### Media

Twitter is a surprisingly helpful place!  People are generally very helpful.  I would recommend following the people below and participating in TidyTuesday challenges. 
    
    - #TidyTuesday
    - #rstats
    - @thomasp85
    - @kdnuggets
    - @hmason
    - @djpatil
    - @NSSDeviations
    - @hspter
    - @kaggle
    - @hugobowne
    - @R4DScommunity
    - @thomas_mock
    - @robinson_es
    - @juliasilge
    - @WeAreRLadies
    - @dataandme
    - @StatGarrett
    - @xieyihui
    - @Rbloggers
    - @drob
    - @hadleywickham

Online Learning Platforms

- DataCamp
- LinkedIn Learning (formerly Lynda)
- Udacity
- Coursera
- Kaggle
- Udemy

YouTube Channels

- [TidyTuesday Screencasts by David Robinson](https://www.youtube.com/user/safe4democracy)
- [Econometrics Academy](https://www.youtube.com/user/econometricsacademy)
- [Ben Lambert's Videos on Advanced Stats](https://www.youtube.com/user/SpartacanUsuals)


Famous Studies

- [Framingham Heart Study](https://en.m.wikipedia.org/wiki/Framingham_Heart_Study)


Other blogs

- [Top 50 Statistics Blogs of 2019](https://www.thebestcolleges.org/rankings/best-statistics-blogs/)
- [R Blogs](https://r-dir.com/community/blogs.html)
